version: "3.3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    #network_mode: "host"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./conf.d:/etc/nginx/conf.d"
      - "/data/nginx/log:/var/log/nginx"
      - "/root/deploy/certbot/ssl:/etc/letsencrypt"
      - "/root/deploy/wordpress/src:/root/deploy/wordpress/src"
