version: '3.3'

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    #network_mode: "host"
    env_file:
      - ".env"
    volumes:
      - "./src:/var/www/html"
    ports:
      - "6131:80"
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
