version: "3.3"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    env_file:
      - ".env"
    ports:
      - "${PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
    volumes:
      - "${DATA_PATH}:/var/lib/mysql"
      - "./mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf"
