version: "3.3"

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "${PORT}:6379"
    restart: always
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - "${DATA_PATH}:/data"
